import type { Metadata } from "next";
import { Inter, Poppins, Sora } from "next/font/google";
import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const inter = Inter({ subsets: ["latin"] , variable:'--font-inter'});
const poppins = Poppins({subsets:["latin"], variable:'--font-poppins', weight:['100', '200', '300', '400', '500', '600', '700', '800', '900']});
const sora = Sora({subsets:['latin'], variable:'--font-sora'})

export const metadata: Metadata = {
  title: "Nabeel's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // className='scroll-smooth'
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.variable} ${sora.variable} ${poppins.variable} bg-[#0f0615] w-screen flex flex-col justify-center items-center overflow-x-hidden`}>{children}</body>
    </html>
  );
}
